### ISSUE TITLE
outcome data

### ISSUE THREAD

**Issue by AMI3** [IBM/wntrac#1]
In your visualization you show the outcomes in the different territories - such as Confirme Cases, Testing, Hospitilazation, Recoveries, Confirmed Deaths.

Can you make this data available (or at least provide a link to the data source) - timeline of these outcomes for the different countries/territories.

Thanks,

Ami Mizrahi
Covid-19 Task Force
MOH, Israel
Ami.mizrahi@moh.gov.il

![NPI and Confirmed example](https://user-images.githubusercontent.com/56076966/91266672-64b79280-e77a-11ea-8904-e660f83d0572.jpg)

**Comment by cwachira** [comment]
Thank you for your interest. 

You can access data for covid-19 outcomes (e.g., cases etc) from the WHO, https://covid19.who.int/table, and ECDC https://www.ecdc.europa.eu which were used to build the visualisation. 

We will update the details behind the visualisation in the website shortly.

Please let us know if there are any other questions. 
We will keep this issue open for a couple of more days.
