### ISSUE TITLE
South Africa NPI dataset is inconsistent with the available SA government website

### ISSUE THREAD

**Issue by cwachira** [IBM/wntrac#2]
I identified 3 issues with the South African NPI response

1. For the event with even_id = 09a4f6aa-dafd-11ea-a5d4-eeee0af7e348 has restriction of 2 which is out of the binary options provided in the taxonomy https://ibm.github.io/wntrac/dataset#data-record

2. There is only one lifting event for SA but from the government website a couple of lifting exists. https://www.gov.za/coronavirus/guidelines

3. Some of the imposing event that exists in this dataset are repeated at different dates for the same event

**Comment by Sha20-ai** [comment]
Thank you for raising the issues. 

The first issue on an event with restriction of 2 has been resolved with the latest update to the database (8c28c98) where such cases were filtered. 

We are working hard to resolve the other issues.

**Comment by Sha20-ai** [comment]
All issues were reviewed, resolved and data updated with the changes.
