### ISSUE TITLE
freedom of movement (nationality dependent), confinement,  2/29/2020, 3/1/2020, USA-NY , imposed , the event: "She went into home isolation with her husband." was tagged as confinement)

### ISSUE THREAD

**Issue by ossnat** [IBM/wntrac#3]
**Describe the issue with the NPI event**

**Provide the NPI event (even_id)**
Please provide the unique id of the NPI event (even_id) having the issue.

**For the evidence sentence(s) unique id (evid_id)**
If there are multiple evidence sentences for that NPI event having data errors, for each evidence sentence, provide the unique id (evid_id)

**Provide the corrected values (as applicable)**
Please provide the corrected: 
- type
- date
- country
- state / province
- whether the NPI was imposed or lifted
- citation_url if available.

**(Optional) Contact Information:**
 - Your name
 - Your affiliated institution

**Additional context**

**Comment by Sha20-ai** [comment]
Thank you for raising the issue. 

We are working on a tool that will help resolve the issue.

**Comment by Sha20-ai** [comment]
This issue was reviewed, resolved and data updated with the change.
