### ISSUE TITLE
freedom of movement reported: 7/11/20 should be 3/11/20. North Dakota. imposed.  "On March 11, the state's first case was confirmed, in Ward County.[4] North Dakota Native American tribes, Standing Rock Sioux and the Turtle Mountain Band of Chippewa, restrict travel into reservations to limit spread of COVID-19.[5]" https://bismarcktribune.com/news/local/health/north-dakota-coronavirus-news-march-11-care-facilities-restrict-visitors/article_42eca49e-0f77-5b3e-91dc-ee0241ad2190.html

### ISSUE THREAD

**Issue by ossnat** [IBM/wntrac#4]
**Describe the issue with the NPI event**

**Provide the NPI event (even_id)**
Please provide the unique id of the NPI event (even_id) having the issue.

**For the evidence sentence(s) unique id (evid_id)**
If there are multiple evidence sentences for that NPI event having data errors, for each evidence sentence, provide the unique id (evid_id)

**Provide the corrected values (as applicable)**
Please provide the corrected: 
- type
- date
- country
- state / province
- whether the NPI was imposed or lifted
- citation_url if available.

**(Optional) Contact Information:**
 - Your name
 - Your affiliated institution

**Additional context**

**Comment by Sha20-ai** [comment]
Thank you for raising the issue. 

We are working on a tool that will help resolve the issue.

**Comment by Sha20-ai** [comment]
This issue was reviewed, resolved and the data updated with the change.
