### ISSUE TITLE
USA-NY mass gathering wrongly reported at 1/4/2020, evidence: 447e7ffa-c4f5-4ca3-b2f8-113182f0a0cf citation: "The ban on large gatherings meant that the annual "First Cast" ceremony at the Junction Pool, a popular fly fishing"

### ISSUE THREAD

**Issue by ossnat** [IBM/wntrac#5]
**Describe the issue with the NPI event**

**Provide the NPI event (even_id)**
Please provide the unique id of the NPI event (even_id) having the issue.

**For the evidence sentence(s) unique id (evid_id)**
If there are multiple evidence sentences for that NPI event having data errors, for each evidence sentence, provide the unique id (evid_id)

**Provide the corrected values (as applicable)**
Please provide the corrected: 
- type
- date
- country
- state / province
- whether the NPI was imposed or lifted
- citation_url if available.

**(Optional) Contact Information:**
 - Your name
 - Your affiliated institution

**Additional context**

**Comment by Sha20-ai** [comment]
Thank you for raising the issue. 

We are working on a tool that will help resolve the issue.

**Comment by Sha20-ai** [comment]
This issue was reviewed, resolved and the data updated with the change.
