### ISSUE TITLE
USA-NY, school closure wrongly reported at 1/5/2020, this is a type, should be May first. citation: "At the beginning of May, when Cuomo announced that the remainder of the school year in the state was canceled, all"

### ISSUE THREAD

**Issue by ossnat** [IBM/wntrac#6]
**Describe the issue with the NPI event**

**Provide the NPI event (even_id)**
Please provide the unique id of the NPI event (even_id) having the issue.

**For the evidence sentence(s) unique id (evid_id)**
If there are multiple evidence sentences for that NPI event having data errors, for each evidence sentence, provide the unique id (evid_id)

**Provide the corrected values (as applicable)**
Please provide the corrected: 
- type
- date
- country
- state / province
- whether the NPI was imposed or lifted
- citation_url if available.

**(Optional) Contact Information:**
 - Your name
 - Your affiliated institution

**Additional context**

**Comment by Sha20-ai** [comment]
Thank you for raising the issue. 

We are working on a tool that will help resolve the issue.

**Comment by Sha20-ai** [comment]
This issue was reviewed, resolved and the data updated with the change.
