### ISSUE TITLE
Inconsistency found in restriction field

### ISSUE THREAD

**Issue by ananya0112** [IBM/wntrac#7]
1. Found evidences with restriction value=2, while the documentation states that 0 and 1 are the only valid values. 
2. Further, within restriction=1, found instances that pertain to the extension of NPI(s).

**Comment by psuryan** [comment]
We recently added the ability to mark NLP extensions in the WNTRAC Curator tooling. These extensions should not have been extracted as part of the dataset. They should have been filtered. With the latest update to the dataset (https://github.com/IBM/wntrac/commit/8c28c980273c60cd3b1b68557f7924d27b2da6a5) we filtered those instances.
