### ISSUE TITLE
Found other event type in NPI

### ISSUE THREAD

**Issue by ananya0112** [IBM/wntrac#8]
Found evidences (over 17) with event type marked as `other` not defined as a part of the original taxonomy.

**Comment by psuryan** [comment]
We recently added the ability to mark certain event types currently not covered by the WNTRAC taxonomy as "other" in the WNTRAC Curator tooling. These events should not have been extracted as part of the dataset. They should have been filtered. With the latest update to the dataset (https://github.com/IBM/wntrac/commit/8c28c980273c60cd3b1b68557f7924d27b2da6a5) we filtered those instances.
